<?php

namespace App\Entity;

use App\Repository\EmployeeRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: EmployeeRepository::class)]
class Employee extends User implements UserInterface
{


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }

    public function getLastname(): ?string
    {
        return parent::getLastname(); // TODO: Change the autogenerated stub
    }
    public function getEmail(): ?string
    {
        return parent::getEmail(); // TODO: Change the autogenerated stub
    }
    public function getRoles(): array
    {
        return parent::getRoles(); // TODO: Change the autogenerated stub
    }
}
