controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute



app_home:
    path: /
    controller: App\Controller\HomeController::index

